### ISSUE TITLE
Feature: Specify a Collection of Players

### ISSUE THREAD

**Issue by MeFisto94** [Bloepiloepi/MinestomParticles#3]
Currently, the particles are broadcast to every player being part of a specific instance, which is probably good in most cases, but maybe adding an override to handle an `Iterable<Player>` or something may be cool, for situations where the user needs more control (e.g. particles that should only be visible for one player).

I can't come up with a more specific use-case though

**Comment by TogAr2** [comment]
It's now possible to draw particles using a `Collection<Player>` (the `Instance` overload is still there)
